Integration of new component visualization options
OpenSmock/Molecule pull request #168
Opened 2024-03-25 10:20 UTC by Eliott-Guevel

2024-03-26 15:06 UTC, labordep commented
@Eliott-Guevel I found a problem in this panel:
![image](https://github.com/OpenSmock/Molecule/assets/49183340/abcb7318-8439-428a-a287-ffe8cc735d39)

From the state of the screenshot (two selected elements):
1 - I click on "Browse" the class *Equipment* is browsed.
2 - I click on *Receiver* in the required list, and I click on "Browse" the class *Equipment* is always browsed

2024-03-26 15:06 UTC, labordep commented
@Eliott-Guevel I found a problem in this panel:
![image](https://github.com/OpenSmock/Molecule/assets/49183340/abcb7318-8439-428a-a287-ffe8cc735d39)

From the state of the screenshot (two selected elements):
1 - I click on "Browse" the class *Equipment* is browsed.
2 - I click on *Receiver* in the required list, and I click on "Browse" the class *Equipment* is always browsed

2024-03-26 15:08 UTC, labordep requested changes
See my bug report in PR comment.

2024-03-27 08:30 UTC, Eliott-Guevel commented
see #172 for a fix

2024-03-28 09:01 UTC, labordep requested changes
@Eliott-Guevel, thanks. I wrote some comment and resquest changes.

2024-03-28 09:01 UTC, labordep commented on src/Molecule-IDE/SpFilteringListDoubleClickPresenter.class.st
I think we need to prefix this classe with Mol. As all molecule classes (normally).

2024-03-28 09:46 UTC, Eliott-Guevel commented on src/Molecule-IDE/SpFilteringListDoubleClickPresenter.class.st
It's a subclass of `SpFilteringListPresenter` which is a Spec class so I don't know if it's relevant to prefix it with Mol

2024-03-28 10:10 UTC, Eliott-Guevel commented on src/Molecule-IDE/MolOptions.class.st
Do its subclasses need to also be suffixed with "Presenter" ?

2024-03-28 12:02 UTC, labordep commented on src/Molecule-IDE/SpFilteringListDoubleClickPresenter.class.st
I know but this is mandatory in case of another loaded project have the same idea :-)

2024-04-02 11:43 UTC, labordep requested changes

2024-04-02 11:43 UTC, labordep commented on src/Molecule-IDE/MolImplementations.class.st
Suffix with Presenter

2024-04-02 11:43 UTC, labordep commented on src/Molecule-IDE-Tests/MolImplementationsTest.class.st
Rename this test class

2024-04-02 11:43 UTC, labordep commented on src/Molecule-IDE/MolInterfaces.class.st
Suffix with Presenter

2024-04-02 11:43 UTC, labordep commented on src/Molecule-IDE-Tests/MolInterfacesTest.class.st
Rename test class

2024-06-14 13:48 UTC, labordep commented
Hi @Eliott-Guevel how this PR is not yet merged?

2024-06-25 07:18 UTC, Eliott-Guevel commented
![image](https://github.com/OpenSmock/Molecule/assets/76944457/2f7f4f6f-9562-4af0-b89b-c484b29ea586)
I don't know if GitHub also shows you this message, but I fixed my code according to your comments so you can merge this pull request since the interfaces function as intended and are named correctly. Thanks

2024-06-26 07:33 UTC, Eliott-Guevel commented
There are no problems with my interfaces using the new main branch with #177 merged.

However, I don't understand why some of `MolComponentManager`'s tests fail sometimes. When executing all of `MolComponentManager`'s tests at the same time, 3 (or less) tests can fail (always the same ones, see Pharo 12 CI as well as `testGarbageCollect `(don't know why `testFlushComponent` is executed 2 times), which is not the case when executing them individually.
Putting relevant variables and going line by line in the debugger isn't useful to identify the fail (doesn't lead to the same result).
My guess is that since the order of tests is random, there's sometimes a bug with cleanUp and not all components are cleaned or something of the sort.

2024-06-27 14:07 UTC, merged

2024-07-02 07:01 UTC, Eliott-Guevel commented
I have no problem using the visualization option (which isn't currently intergrated to Molecule) with #177, it could be merged in the near future