Fix #170: Add announcements for component life-cycle + unit tests.
OpenSmock/Molecule pull request #177
Opened 2024-04-07 17:13 UTC by labordep

Minor cleanup.

2024-04-10 14:54 UTC, ELePors requested changes
We should add a cleanup process for announcement

2024-04-10 14:54 UTC, ELePors commented on src/Molecule-Tests/MolComponentAnnouncementTest.class.st
We should add a test for cleaning process

2024-05-14 09:46 UTC, labordep commented
@ELePors Can you send your code into this branch?

2024-05-24 13:26 UTC, labordep commented
> @ELePors Can you send your code into this branch?

Up :)

2024-06-14 13:49 UTC, labordep commented
@ELePors, @Eliott-Guevel is waiting for your commit. Thanks.

2024-06-25 14:20 UTC, labordep commented
👍

2024-06-25 14:25 UTC, labordep reviewed
Ok!

2024-06-25 14:27 UTC, merged