Deprecated instanciate in favor of instantiation (correct grammatical…
OpenSmock/Molecule pull request #98
Opened 2023-09-19 09:38 UTC by Eliott-Guevel

Deprecated instanciate in favor of instantiation (correct grammatical… form). Same for instanciation which needs to be replaced by instantiation
This commit fixes #97

2023-09-19 09:48 UTC, labordep requested changes
You need to use auto correction function of the deprecation :

```smalltalk
self deprecated: 'Example of a deprecated method with transform'
       transformWith: '`@receiver deprecatedMethod' -> '`@receiver newMethod'
```

2023-09-21 14:26 UTC, labordep commented
Waiting for https://github.com/pharo-project/pharo/issues/14697 analysis.

2023-09-21 15:46 UTC, labordep requested changes
Deprecated methods should call directly the new methods. This is not useful to conserve each old implementation.
For example : 

```smalltalk
MolComponentImpl classSide >> instanciate 

self deprecated: 'Use instantiate' transformWith: '`@receiver instanciate' -> '`@receiver instantiate'.

^ self instantiate 

```

2023-09-25 18:19 UTC, labordep commented
> Deprecated methods should call directly the new methods. This is not useful to conserve each old implementation.
> 
> For example : 
> 
> 
> 
> ```smalltalk
> 
> MolComponentImpl classSide >> instanciate 
> 
> 
> 
> self deprecated: 'Use instantiate' transformWith: '`@receiver instanciate' -> '`@receiver instantiate'.
> 
> 
> 
> ^ self instantiate 
> 
> 
> 
> ```

@Eliott-Guevel have you seen my review ?

2023-09-26 08:27 UTC, Eliott-Guevel commented
I've just made the adapted modifications

2023-09-28 15:44 UTC, labordep requested changes
Examples from GPS should not be here (this is not a PR related to that) - see review for others feedback.
Ok for my first review.

2023-09-28 15:44 UTC, labordep commented on Molecule-Examples/MolGNSSGalileo.class.st
> +Class {
Examples from GPS should not be here (this is not a PR related to that)

2023-09-28 15:44 UTC, labordep commented on Molecule-Tests/MolHomeServicesTest.class.st
>  Class {
Can you reformat the code as previous ? (One line at each instructions)

2023-09-29 07:00 UTC, Eliott-Guevel reviewed
Removed classes enhancing the GPS example (are put in another branch of my Molecule fork which is associated to another pull request

2023-10-03 12:42 UTC, labordep commented
Hum this PR is very strange because its appears that all the code of molecule have been modified !

2023-10-10 15:38 UTC, labordep commented
I have the explanation :  

```
I just wanted to let people who are using Pharo12 that they might notice some changes while exporting their code to github now.

We are introducing a TonelV3 format. The goals are to:
- Follow the spec that was agreed upon because currently we have symbols instead of strings in some places and that made it incompatible with Gemstone or Vast 
- Add missing informations. This is because in Pharo we have packages and tags but the only thing exported is the category. So reading the categories was ambiguous and relied on some heuristic. Loading the same class in two pharo image could load the class in different packages depending on the state of the image. 
- We want to add meta data for new features (not yet done). For example there is a new feature to rename a class and keep the old name as a deprecated alias for a while. We would like to be able to declare those info in the fluid class definition and in the Tonel format.

The new format still exports the category (but there is a setting to not export it) to stay backward compatible for now. 
Using the Tonel paser to read classes that were exported before Pharo 12 can have some difficulties to manage the tags, but the TonelReader class that is used by Iceberg knows how to resolve all of those problem to ensure the classes are in the right packages and in the right classes!
```

So don't use Pharo 12 for this work. Can you re send your modifications with P11 ? Thanks.

2023-10-23 07:38 UTC, Eliott-Guevel commented
I've made the modifications with Pharo 11, it should now only modify the relevant files

2023-10-24 07:56 UTC, closed without merging